--- 
- hosts: 172.31.10.94
  become: yes
  tasks:
    - name: i want to execute linux command
      command: hostname -f 
      register: myResult 

    - name: i want display fisrttask result 
      debug:
        msg: "{{myResult}}"