--- 
- hosts: 172.31.10.94
  become: yes
  tasks:
    - name: i want to run linux command
      command: hostname -f
      register: myresult


    - name: i want dsplay linux command output 
      debug:
        msg: "{{myresult}}"


    