--- 
- hosts: mywebservernodes
  become: yes
  vars:
     myvar1: tree
     myvar2: wget
     myvar3: git
  tasks:
     - name : i want display varaible value
       debug:
         msg: "{{myvar1}}"
