---
# tasks file for mytomcatrole for ubuntu 18.04
- include_tasks: installjava.yml
- include_tasks: createtomcatuser.yml
- include_tasks: installtomcat.yml
- include_tasks: updatepermission.yml
- include_tasks: tomcatservice.yml
- include_tasks: servicestart.yml
- include_tasks: tomcatwebmgement.yml
- include_tasks: depolyjavaapp.yml
- include_tasks: restarttomcat.yml
