# Step 4.1 —  Give the tomcat group ownership
- name: Give the tomcat group ownership
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat
   
# Step 4.2 — give the tomcat group read access to the conf directory and all of its contents, 
- name: Change file ownership, group and permissions
  file:
    path: /opt/tomcat/conf
    recurse: yes
    mode: g+r
    state: directory

# Step 4.3 — give the tomcat group excute access to the conf directory and all of its contents, 
- name: Change file ownership, group and permissions
  file:
    path: /opt/tomcat/conf
    mode: g+x
    state: directory

# Step 4.4 — Make the tomcat user the owner of the webapps, work, temp, and logs directories
- name: Change file ownership, group and permissions
  file:
    path: /opt/tomcat/webapps
    recurse: yes
    user: tomcat
    state: directory


- name: Change file ownership of work
  file:
    path: /opt/tomcat/work
    recurse: yes
    owner: tomcat
    state: directory   

- name: Change file ownership of temp
  file:
    path: /opt/tomcat/temp
    recurse: yes
    owner: tomcat
    state: directory

- name: Change file ownership logs
  file:
    path: /opt/tomcat/logs
    recurse: yes
    owner: tomcat
    state: directory
